name: oim
description: A Flutter application with desktop UI and C/C++ backend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffi: ^2.1.0
  desktop_multi_window: ^0.2.1
  path_provider: ^2.1.0
  url_launcher: ^6.1.11
  crypto: ^3.0.3
  http: ^1.1.0
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
