[package]
name = "mls_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
openmls = "0.8"
openmls_rust_crypto = "0.5"
openmls_basic_credential = "0.5"
openmls_traits = "0.5"
tls_codec = "0.4"
base64 = "0.22"
serde_json = "1"

[profile.release]
opt-level = 2
